environment:
  name: mock

# do not change it as it is validated by the component tests
baseUrl: "https://mock-blueprint.com"

management.server.port: 0 #use a random port each time

spring:
  data:
    mongodb:
      authentication-database: admin
      database: lc-mock-blueprint-addon
      uri: mongodb://localhost:27017
      ssl-enabled: false
  main:
    allow-bean-definition-overriding: true